### PR TITLE
web: add hijack grace period

### PR DESCRIPTION
**Pull request by pivotal-jwinters**

### CODE REVIEW

**Comment by pivotal-jwinters** [comment]
@cirocosta when do we need a version bump?

some commits don't seem to have them
e01c00368d282b9b96cfb9ffccfdfcc0dcf906b2

**Comment by xtremerui** [comment]
@pivotal-jwinters for some older commits it was not required for bumping version but we started to do that to follow the standard guids of helm/charts. It looks like all PRs there include a version bump always. 

Though I am not sure why the commit you posted doesn't bump version. Maybe it is committed directly but not through PR?

**Comment by cirocosta** [comment]
@xtremerui @pivotal-jwinters  that commit was part of a series of others - given that the merge wasn't done after a squash, the commit itself doesn't have a bump, but the series does :grin:

**Comment by cirocosta** [comment]
@taylorsilva you might've told me this 10000 times hahah buuuut, should this PR get into master? this is adding values for a feature that's not part of 6.0.0 (but instead for the next release)

**Comment by xtremerui** [comment]
@cirocosta while I worked on those release pipelines I think we should make the versioning of chart on sync with concourse. In this case, this PR should go to master, since it is a change that matches the change of concourse binary that aims for next minor release (next minor release of concourse binary should be bandled on release-6.0.x pipeline).

If later we decided this is sth need to be back ported for 6.0.x, then it should then be cherry-picked back to release/6.0.x branch of concourse-chart.

**Comment by taylorsilva** [comment]
@cirocosta You are kindaaaa right. Ideally this should go to dev but we haven't integrated the workflow into the main pipeline yet. Might hack on this tomorrow and close the loop

**Comment by xtremerui** [comment]
@pivotal-jwinters  could you just rebase and update the vesion?

**Comment by pivotal-jwinters** [comment]
@xtremerui fixed

**Pull request merged**
