### PR TITLE
web: allow to override command and args

### PR DESCRIPTION
**Pull request by eonpatapon**
# Existing Issue

It is currently not possible to change the way concourse-web is started without building a new docker image with a custom entrypoint.

# Changes proposed in this pull request

Allow to override the docker image entrypoint by specifying a `command`.
Allow to change the default `args` of the `command`

# Contributor Checklist
> Are the following items included as part of this PR? Please delete checkbox items that don't apply.
- [x] Variables are documented in the `README.md`

# Reviewer Checklist
> This section is intended for the core maintainers only, to track review progress. Please do not
> fill out this section.
- [x] Code reviewed
- [ ] Topgun tests run
- [ ] Back-port if needed

### CODE REVIEW

**Comment by pivotal-izabela-gomes** [comment]
Hey @eonpatapon , sorry for the delay! Can you share the use case that justifies that change? I also have a follow-up question, wouldn't a similar approach be useful for running a worker too?

**Comment by eonpatapon** [comment]
@pivotal-izabela-gomes hi! The use case is that we retrieve some secrets for concourse with vault-injector. We want to source files generated by vault-injector to make some environment variables available to concourse. So basically we override the command to "bash -ce 'source file && concourse web'"

**Comment by eonpatapon** [comment]
As for the worker we deploy it in VM so I didn't think of modifying the chart for it, but I can do it

**Comment by pivotal-izabela-gomes** [comment]
Thanks for clarifying it to me, @eonpatapon ! Can you update Charts.yaml and bump the [chart version](https://github.com/concourse/concourse-chart/blob/40f5c8107ef45cc55f09484d96051d4a61128bda/Chart.yaml#L3) so our check passes and I can then merge your PR? It would be a patch bump in this case.

**Comment by pivotal-izabela-gomes** [comment]
@eonpatapon Hey, one of our checks didn't pass. Your last commit was not signed off: https://github.com/concourse/concourse-chart/pull/95/checks?check_run_id=651906768 
Can you submit that change? Thanks

**Pull request merged**
