### PR TITLE
Add CONCOURSE_GARDEN_REQUEST_TIMEOUT config

### PR DESCRIPTION
**Pull request by deniseyu**
* In 5.7.1, we added this configuration option as part of
[#4707](https://github.com/concourse/concourse/pull/4707)

Co-authored-by: Ciro S. Costa
Signed-off-by: Denise Yu <dyu@pivotal.io>

### CODE REVIEW

**Comment by cirocosta** [comment]
marking it as `wip` so that we merge this in after we get a `develop` branch in here (like how we do for `concourse-bosh-deployment`) - see https://github.com/pivotal/concourse-ops/issues/117#issuecomment-550000311 😁

**Comment by cirocosta** [comment]
(blocked on https://github.com/concourse/concourse-chart/issues/13)

**Comment by deniseyu** [comment]
I think we need this to be part of the 5.7.1 patch or else the `k8s-check-params` job will fail. @cirocosta @taylorsilva @pivotal-bin-ju is it okay to defer changing the workflow until after the patch goes out?

**Comment by taylorsilva** [comment]
I think it's fine to merge this in right now. We just don't want to start merging in too many changes without our processes fleshed out.

This PR would also fix #5

**Pull request merged**
