### PR TITLE
Add trace flags to worker

### PR DESCRIPTION
**Pull request by taylorsilva**
added in concourse/concourse#7487

# Contributor Checklist
- [x] Variables are documented in the `README.md`
- [x] Which branch are you merging into?
    - `master` is for changes related to the current release of the `concourse/concourse:latest` image and should be good to publish immediately
    - `dev` is for changes related to the next release of Concourse (aka unpublished code on `master` in [concourse/concourse](https://github.com/concourse/concourse))

### CODE REVIEW

**Review by muntac — CHANGES_REQUESTED** [review]
Looks good! But I think you forgot the item in the checklist about documenting the variables in the `README`.

**Comment by taylorsilva** [comment]
@muntac that only applies to the k8s specific stuff. None of the Concourse flags/env vars are in the README.

That actually made me notice that the containerd stuff looks like it may be in the wrong section...

**Comment by taylorsilva** [comment]
ah okay it's not!

So all the flags/env vars fall under the [`concourse.<worker/web>`](https://github.com/concourse/concourse-chart/blob/95c45c237851f4717d7d72bf8c93af467298cbb3/values.yaml#L52-L56) key. All the k8s specific stuff is under the top-level [`web`](https://github.com/concourse/concourse-chart/blob/95c45c237851f4717d7d72bf8c93af467298cbb3/values.yaml#L1833) or [`worker`](https://github.com/concourse/concourse-chart/blob/95c45c237851f4717d7d72bf8c93af467298cbb3/values.yaml#L2210) keys.

Looks like the README has the containerd stuff listed under `worker.containerd.` when it should be `concourse.worker.containerd`. Oops!

**Review by muntac — APPROVED** [review]
oh wow TIL! LGTM!

**Pull request merged**
