### PR TITLE
Make CONCOURSE_ENABLE_RERUN_WHEN_WORKER_DISAPPEARS configurable

### PR DESCRIPTION
**Pull request by muntac**
This feature was added to the web command in concourse/concourse#5192. Adding flag to Helm chart for parity.

### CODE REVIEW

**Comment by taylorsilva** [comment]
@muntac Can you switch this PR to target the `dev` branch instead? The `helm-check-params` job does it's check against that branch ([source](https://github.com/concourse/ci/blob/f6300a55a20b85d71959c089b44a71c065909e88/pipelines/concourse.yml#L1967-L1972)). 

Basically anything that is related to something not available in the currently available concourse binary and docker images goes into the dev branch. When `6.2.0` comes out we'll merge dev back into master.

No need to bump the chart version either when PR'ing to `dev`.

**Comment by muntac** [comment]
@taylorsilva thanks for looking into this! switched the base to `dev` but now the version-bump-check in https://ci.concourse-ci.org/builds/1210579 is failing. Should that job be removed from the `helm-prs-dev` pipeline? We can do that if that's the case.

**Comment by taylorsilva** [comment]
@muntac I actually want to remove it from all of the helm-prs pipelines haha
I'll do that now, I've been thinking about it all week, kinda on the fence. I'm worried about accidentally releasing the same version of the chart multiple times 😨

**Comment by taylorsilva** [comment]
Removed the version bump check and now I don't know how to clear the check on the PR 😅

**Comment by muntac** [comment]
Thanks! We'll merge it in since that check should no longer exists.

**Pull request merged**
