### PR TITLE
fix: provide CONCOURSE_VAULT_AUTH_PARAM for ldap backend

### LINKED ISSUE #222: CONCOURSE_VAULT_AUTH_PARAM not populated for LDAP backend
Currently when using `CONCOURSE_VAULT_AUTH_BACKEND=ldap` the `CONCOURSE_VAULT_AUTH_PARAM` will not get set.  `CONCOURSE_VAULT_AUTH_PARAM` seems to be directly tied to `approle` in this chart.

https://github.com/concourse/concourse-chart/blob/7c2e39da64d822109f64391d741b59d69924ecd0/templates/web-deployment.yaml#L549-L555

### PR DESCRIPTION
**Pull request by jmccann**
# Existing Issue

Fixes #222 

# Why do we need this PR?

Allow setting `CONCOURSE_VAULT_AUTH_PARAM` when using `CONCOURSE_VAULT_AUTH_BACKEND=ldap`

# Contributor Checklist

- [ ] Variables are documented in the `README.md`
- [ ] Which branch are you merging into?
    - `master` is for changes related to the current release of the `concourse/concourse:latest` image and should be good to publish immediately
    - `dev` is for changes related to the next release of Concourse (aka unpublished code on `master` in [concourse/concourse](https://github.com/concourse/concourse))

# Reviewer Checklist
> This section is intended for the core maintainers only, to track review progress. Please do not
> fill out this section.
- [ ] Code reviewed
- [ ] Topgun tests run
- [ ] Back-port if needed
- [ ] Is the correct branch targeted? (`master` or `dev`)

### CODE REVIEW

**Comment by xtremerui** [comment]
Hi could you please fix the DCO error?

**Comment by jmccann** [comment]
@xtremerui This is done ✅ !  Thanks!

**Comment by xtremerui** [comment]
I have limited knowledge of vault auth backend. However from the https://www.vaultproject.io/api-docs/auth list I can see there are multiple auth backends available. `approle` and `ldap` are only two of them.

So I wonder is there any other vault auth backend that also needs params when login through Concourse? In this case we might want to update the condition of setting `CONCOURSE_VAULT_AUTH_PARAM` in chart. WDYT?

**Comment by jmccann** [comment]
@xtremerui I'm not sure if/what all could require it.

Should I have some sort of "enable" flag for this?  Maybe `concourse.web.vault.useAuthParam=true/false`?  It'd be a breaking change then too, right?

**Comment by xtremerui** [comment]
I think removing the `if` condition is fine. So user could decide if they want to include auth params without worring about what auth backend it is. Ultimately freedom :)

**Comment by jmccann** [comment]
I think the issue is then it'd expect the secret to be provided.  So if they don't need it there would be a secret lookup on a secret that does not exist.

That's why I'm wondering if we need to have some toggle to control trying to load that secret or not.

**Comment by xtremerui** [comment]
why would it be error? we have a default value in 
https://github.com/concourse/concourse-chart/blob/41a46463a2f3b165a80fbc9fb9137e3f735c224d/templates/web-secrets.yaml#L97

so if users don't need it they can just leave it unset in values.yml. Do you mean the error in helm or concourse?

**Comment by jmccann** [comment]
> why would it be error? we have a default value in

We are managing the secrets outside of the chart (`secrets.create=false`).  If someone is manually managing their secrets they may not have secrets defined that they don't actually need/use.

I worry about a use-case where for example someone is using vault with the `cert` backend.  They wouldn't use `vault-client-auth-param`.  They don't have (and I don't think they should need) a blank `vault-client-auth-param` in their secrets they are manually managing.  So wrapping the `CONCOURSE_VAULT_AUTH_PARAM` in the deployment template with something like `concourse.web.vault.useAuthParam` allows them to not include a secret they don't need ... but if they need the secret they can provide it and enable the use of it.

This is similar to CA certs.  Not everyone needs to specify a CA cert.  They can control with `concourse.web.vault.useCaCert` if they are providing it or not. https://github.com/concourse/concourse-chart/blob/36ddb7589d7e2a7ba908a1bdd6336fa85fcb48d6/templates/web-deployment.yaml#L1513-L1516

Then they don't need to include the secret `vault-ca-cert ` in their secrets if they don't use/need it.

https://github.com/concourse/concourse-chart/blob/41a46463a2f3b165a80fbc9fb9137e3f735c224d/templates/web-secrets.yaml#L93

**Comment by xtremerui** [comment]
@jmccann thx for the explaination. I think it makes sense.

We will make sure this change goes with a minor release then.

**Review by xtremerui — APPROVED** [review]

**Pull request merged**
